services:
  - type: web
    name: tcc-stockflow
    env: docker
    envVars:
      - key: DOCUMENT_ROOT
        value: public
      - key: DB_HOST
        value: db.cvakzvhqfgccjwohmmjh.supabase.co
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres
      - key: DB_PASS
        sync: false
      - key: DB_SSLMODE
        value: require
